// Robot vacuum database — add new entries here following the same structure
//
// pris_uppskattning : rekommenderat / officiellt SE-pris (kr)
// pris_prisjakt     : lägsta hittade pris från svenska butiker maj 2026 (null = ej hittad)
//
// Källor: se.roborock.com · se.dreametech.com · narwal.se · irobot.se
//         pricerunner.se · webhallen.com · vacuumwars.com

const produkter = [

  // ══════════════════════════════════════════════════════
  //  2024-modeller
  // ══════════════════════════════════════════════════════

  {
    tillverkare: "Roborock",
    modellnamn: "S8 MaxV Ultra",
    pris_uppskattning: 13990,
    pris_prisjakt: 7290,
    sugkraft: 10000,
    navigering: "LiDAR",
    hinderdetektion: "AI-kamera + 3D-strukturerat ljus",
    moppteknik: "Vibrerande + lyftbar",
    borstar: "Gummiborstar",
    tomningsstation_liter: 2.5,
    klattring_mm: 20,
    filtyp: "HEPA",
    ar: 2024
  },
  {
    tillverkare: "Roborock",
    modellnamn: "Qrevo Curv",
    pris_uppskattning: 11990,
    pris_prisjakt: 8159,
    sugkraft: 18500,
    navigering: "LiDAR",
    hinderdetektion: "AI-kamera",
    moppteknik: "Roterande + lyftbar",
    borstar: "Gummiborstar",
    tomningsstation_liter: 3.0,
    klattring_mm: 22,
    filtyp: "HEPA",
    ar: 2024
  },
  {
    tillverkare: "Dreame",
    modellnamn: "X40 Ultra",
    pris_uppskattning: 11990,
    pris_prisjakt: 5990,
    sugkraft: 12000,
    navigering: "LiDAR",
    hinderdetektion: "AI-kamera (280+ objekt)",
    moppteknik: "Roterande + lyftbar",
    borstar: "Gummiborstar",
    tomningsstation_liter: 3.2,
    klattring_mm: 22,
    filtyp: "HEPA",
    ar: 2024
  },
  {
    tillverkare: "Narwal",
    modellnamn: "Freo Z Ultra",
    pris_uppskattning: 11900,
    pris_prisjakt: 7147,
    sugkraft: 12000,
    navigering: "LiDAR",
    hinderdetektion: "Dual AI-kamera (RGB)",
    moppteknik: "Roterande",
    borstar: "Gummiborstar",
    tomningsstation_liter: 4.0,
    klattring_mm: 18,
    filtyp: "HEPA",
    ar: 2024
  },
  {
    tillverkare: "Narwal",
    modellnamn: "Freo X Ultra",
    pris_uppskattning: 8990,
    pris_prisjakt: 5290,
    sugkraft: 8200,
    navigering: "LiDAR SLAM 4.0",
    hinderdetektion: "AI-kamera + ultraljud",
    moppteknik: "Roterande",
    borstar: "Gummiborstar",
    tomningsstation_liter: 3.5,
    klattring_mm: 18,
    filtyp: "HEPA",
    ar: 2024
  },
  {
    tillverkare: "iRobot",
    modellnamn: "Roomba Combo 10 Max",
    pris_uppskattning: 12999,
    pris_prisjakt: 6796,
    sugkraft: 3500,
    navigering: "Kamera + AI",
    hinderdetektion: "AI-kamera + IR",
    moppteknik: "Vibrerande + lyftbar",
    borstar: "Gummiborstar",
    tomningsstation_liter: 2.5,
    klattring_mm: 18,
    filtyp: "HEPA",
    ar: 2024
  },

  // ══════════════════════════════════════════════════════
  //  2025-modeller
  // ══════════════════════════════════════════════════════

  {
    tillverkare: "Roborock",
    modellnamn: "Saros 10",
    pris_uppskattning: 16990,
    pris_prisjakt: 11649,
    sugkraft: 22000,
    navigering: "LiDAR",
    hinderdetektion: "AI-kamera (RGB) + infällt LDS",
    moppteknik: "Vibrerande + lyftbar",
    borstar: "Gummiborstar",
    tomningsstation_liter: 2.5,
    klattring_mm: 20,
    filtyp: "HEPA",
    ar: 2025
  },
  {
    tillverkare: "Roborock",
    modellnamn: "Saros 10R",
    pris_uppskattning: 11490,
    pris_prisjakt: 9490,
    sugkraft: 22000,
    navigering: "LiDAR (infällt)",
    hinderdetektion: "AI-kamera (RGB) + ultraljud",
    moppteknik: "Vibrerande + lyftbar",
    borstar: "Gummiborstar",
    tomningsstation_liter: 3.0,
    klattring_mm: 20,
    filtyp: "HEPA",
    ar: 2025
  },
  {
    tillverkare: "Roborock",
    modellnamn: "Saros Z70",
    pris_uppskattning: 18990,
    pris_prisjakt: 18990,
    sugkraft: 22000,
    navigering: "LiDAR",
    hinderdetektion: "AI-kamera + 5-axlig robotarm",
    moppteknik: "Vibrerande + lyftbar",
    borstar: "Gummiborstar",
    tomningsstation_liter: 2.5,
    klattring_mm: 20,
    filtyp: "HEPA",
    ar: 2025
  },
  {
    tillverkare: "Roborock",
    modellnamn: "Qrevo Curv X",
    pris_uppskattning: 14389,
    pris_prisjakt: 10225,
    sugkraft: 22000,
    navigering: "LiDAR",
    hinderdetektion: "AI-kamera + ultraljud",
    moppteknik: "Roterande + lyftbar",
    borstar: "Gummiborstar",
    tomningsstation_liter: 3.0,
    klattring_mm: 40,
    filtyp: "HEPA",
    ar: 2025
  },
  {
    tillverkare: "Dreame",
    modellnamn: "X50 Ultra",
    pris_uppskattning: 15990,
    pris_prisjakt: 9468,
    sugkraft: 20000,
    navigering: "LiDAR + VersaLift",
    hinderdetektion: "AI-kamera (280+ objekt)",
    moppteknik: "Roterande + lyftbar",
    borstar: "Gummiborstar",
    tomningsstation_liter: 3.2,
    klattring_mm: 40,
    filtyp: "HEPA",
    ar: 2025
  },
  {
    tillverkare: "Ecovacs",
    modellnamn: "Deebot T30S Pro",
    pris_uppskattning: 7990,
    pris_prisjakt: 7890,
    sugkraft: 11000,
    navigering: "LiDAR (TrueMapping 2.0)",
    hinderdetektion: "AI-kamera + 3D-strukturerat ljus",
    moppteknik: "Roterande + lyftbar",
    borstar: "Gummiborstar",
    tomningsstation_liter: 2.5,
    klattring_mm: 18,
    filtyp: "HEPA",
    ar: 2025
  },
  {
    tillverkare: "Narwal",
    modellnamn: "Freo Z10 Ultra",
    pris_uppskattning: 15490,
    pris_prisjakt: 11490,
    sugkraft: 20000,
    navigering: "LiDAR",
    hinderdetektion: "Dual AI-kamera (RGB) + ultraljud",
    moppteknik: "Roterande",
    borstar: "Gummiborstar",
    tomningsstation_liter: 4.0,
    klattring_mm: 20,
    filtyp: "HEPA",
    ar: 2025
  },
  {
    tillverkare: "Narwal",
    modellnamn: "Flow",
    pris_uppskattning: 15990,
    pris_prisjakt: 15990,
    sugkraft: 30000,
    navigering: "LiDAR (Narmind AI)",
    hinderdetektion: "AI-kamera",
    moppteknik: "Roterande",
    borstar: "Gummiborstar",
    tomningsstation_liter: 4.0,
    klattring_mm: 20,
    filtyp: "HEPA",
    ar: 2025
  },
  {
    tillverkare: "Shark",
    modellnamn: "PowerDetect ThermaCharged",
    pris_uppskattning: 7990,
    pris_prisjakt: null,
    sugkraft: 6000,
    navigering: "LiDAR",
    hinderdetektion: "AI-kamera + IR",
    moppteknik: "Vibrerande",
    borstar: "Kombination",
    tomningsstation_liter: 2.0,
    klattring_mm: 18,
    filtyp: "HEPA",
    ar: 2025
  },
  {
    tillverkare: "Shark",
    modellnamn: "PowerDetect UV Reveal",
    pris_uppskattning: 8990,
    pris_prisjakt: null,
    sugkraft: 6000,
    navigering: "LiDAR",
    hinderdetektion: "AI-kamera + UV + IR",
    moppteknik: "Vibrerande",
    borstar: "Kombination",
    tomningsstation_liter: 2.5,
    klattring_mm: 18,
    filtyp: "HEPA",
    ar: 2025
  },

  // ══════════════════════════════════════════════════════
  //  2026-modeller
  // ══════════════════════════════════════════════════════

  {
    tillverkare: "Dreame",
    modellnamn: "X60 Ultra",
    pris_uppskattning: 13990,
    pris_prisjakt: 14990,
    sugkraft: 35000,
    navigering: "LiDAR (ultratunt 7,95 cm)",
    hinderdetektion: "AI-kamera (280+ objekt)",
    moppteknik: "Roterande + lyftbar",
    borstar: "Gummiborstar",
    tomningsstation_liter: 3.5,
    klattring_mm: 22,
    filtyp: "HEPA",
    ar: 2026
  },
  {
    tillverkare: "Dreame",
    modellnamn: "X60 Max Ultra Complete",
    pris_uppskattning: 17990,
    pris_prisjakt: null,
    sugkraft: 35000,
    navigering: "LiDAR (ultratunt 7,95 cm)",
    hinderdetektion: "AI-kamera (280+ objekt)",
    moppteknik: "Roterande + lyftbar",
    borstar: "Gummiborstar",
    tomningsstation_liter: 5.0,
    klattring_mm: 22,
    filtyp: "HEPA",
    ar: 2026
  },
  {
    tillverkare: "Dreame",
    modellnamn: "L60 Ultra Pro",
    pris_uppskattning: 11990,
    pris_prisjakt: null,
    sugkraft: 35000,
    navigering: "LiDAR",
    hinderdetektion: "AI-kamera",
    moppteknik: "Roterande",
    borstar: "Gummiborstar",
    tomningsstation_liter: 3.0,
    klattring_mm: 21,
    filtyp: "HEPA",
    ar: 2026
  },
  {
    tillverkare: "Ecovacs",
    modellnamn: "Deebot X12 OmniCyclone",
    pris_uppskattning: 12990,
    pris_prisjakt: 13999,
    sugkraft: 22000,
    navigering: "LiDAR + kamera",
    hinderdetektion: "AI-kamera + 3D-strukturerat ljus",
    moppteknik: "Roterande",
    borstar: "Kombination",
    tomningsstation_liter: 3.5,
    klattring_mm: 21,
    filtyp: "HEPA",
    ar: 2026
  },
  {
    tillverkare: "Narwal",
    modellnamn: "Flow 2",
    pris_uppskattning: 11990,
    pris_prisjakt: null,
    sugkraft: 30000,
    navigering: "LiDAR (Narmind Pro AI)",
    hinderdetektion: "AI-kamera",
    moppteknik: "Roterande",
    borstar: "Gummiborstar",
    tomningsstation_liter: 4.0,
    klattring_mm: 20,
    filtyp: "HEPA",
    ar: 2026
  },
  {
    tillverkare: "Narwal",
    modellnamn: "Flow 2 Ultra",
    pris_uppskattning: 14990,
    pris_prisjakt: null,
    sugkraft: 31000,
    navigering: "LiDAR (Narmind Pro AI)",
    hinderdetektion: "AI-kamera + ultraljud",
    moppteknik: "Roterande",
    borstar: "Gummiborstar",
    tomningsstation_liter: 5.0,
    klattring_mm: 20,
    filtyp: "HEPA",
    ar: 2026
  }
];
